version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.20.0
    steps:
      - checkout
      - run: npm install
      - run: npm run check
      - run: npm run lint
      - run: npm test
