name: Sanitize site

on:
# TODO: Disable for now.
#   schedule:
#     - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      age_days:
        description: 'Folder age in days'
        required: false
        default: 3

jobs:
  sanitize:
    name: Check outdated folders
    runs-on: ubuntu-latest

    environment: s3-site

    env:
      file_name: _CLOSED.txt
      AWS_ENDPOINT_URL: ${{ vars.ENDPOINT_URL }}
      AWS_DEFAULT_REGION: ${{ vars.REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}

    steps:
      - name: Checkout script
        uses: actions/checkout@v6
        with:
          sparse-checkout: ./tools/remove-outdated-folders.sh
          sparse-checkout-cone-mode: false
      - name: Check bucket folders
        run: sh ./tools/remove-outdated-folders.sh ${{ vars.BUCKET }} ${{ env.file_name }} ${{ inputs.age_days }}
